/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const AMCType = IDL.Variant({
  'serviceWithParts50' : IDL.Null,
  'onlyService' : IDL.Null,
  'serviceWithParts' : IDL.Null,
});
export const ContractStatus = IDL.Variant({
  'active' : IDL.Null,
  'pendingRenewal' : IDL.Null,
  'expired' : IDL.Null,
});
export const AMCServiceEntry = IDL.Record({
  'serviceDate' : Time,
  'followUpNeeded' : IDL.Bool,
  'contractType' : AMCType,
  'priceReduction' : IDL.Opt(
    IDL.Record({
      'partsName' : IDL.Text,
      'discountPrice' : IDL.Text,
      'regularPrice' : IDL.Text,
    })
  ),
  'amcServiceId' : IDL.Nat,
  'notes' : IDL.Text,
  'partsReplaced' : IDL.Text,
  'customerServiceId' : IDL.Nat,
  'contractStatus' : ContractStatus,
});
export const ServiceType = IDL.Variant({
  'repair' : IDL.Null,
  'cleaning' : IDL.Null,
  'other' : IDL.Text,
  'maintenance' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'cash' : IDL.Null,
});
export const AMCDetails = IDL.Record({
  'id' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'durationYears' : IDL.Nat,
  'contractType' : AMCType,
  'contractEndDate' : Time,
  'remainingBalance' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'notes' : IDL.Text,
  'contractStartDate' : Time,
});
export const AMCContract = IDL.Record({
  'endDate' : Time,
  'owner' : IDL.Principal,
  'contractType' : AMCType,
  'amount' : IDL.Nat,
  'startDate' : Time,
});
export const WarrantyStatus = IDL.Variant({
  'outWarranty' : IDL.Null,
  'inWarranty' : IDL.Null,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'amcServices' : IDL.Vec(AMCServiceEntry),
  'model' : IDL.Text,
  'serviceType' : ServiceType,
  'contact' : IDL.Text,
  'owner' : IDL.Principal,
  'nextServiceDate' : Time,
  'amcDetails' : IDL.Opt(AMCDetails),
  'name' : IDL.Text,
  'amcContracts' : IDL.Vec(AMCContract),
  'serviceInterval' : IDL.Nat,
  'brand' : IDL.Text,
  'warrantyStatus' : WarrantyStatus,
  'installationDate' : Time,
});
export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'sentStatus' : IDL.Bool,
  'description' : IDL.Text,
  'reminderDate' : Time,
  'customerId' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'free' : IDL.Null,
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const ServiceEntry = IDL.Record({
  'id' : IDL.Nat,
  'serviceDate' : Time,
  'serviceType' : ServiceType,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : IDL.Opt(PaymentMethod),
  'owner' : IDL.Principal,
  'isFree' : IDL.Bool,
  'notes' : IDL.Text,
  'customerId' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AMCRevenue = IDL.Record({
  'completedAmount' : IDL.Nat,
  'inProgressAmount' : IDL.Nat,
  'remainingBalance' : IDL.Nat,
  'totalAmount' : IDL.Nat,
});
export const CustomerRevenueBreakdown = IDL.Record({
  'customerName' : IDL.Text,
  'contractType' : IDL.Opt(AMCType),
  'paidServicesCount' : IDL.Nat,
  'amcRenewalCount' : IDL.Nat,
  'customerId' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'freeServicesCount' : IDL.Nat,
});
export const PaymentMethodBreakdown = IDL.Record({
  'cashPayments' : IDL.Nat,
  'upiPayments' : IDL.Nat,
});
export const RevenueByPeriod = IDL.Record({
  'paidServicesCount' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'freeServicesCount' : IDL.Nat,
});
export const ImportCustomerData = IDL.Record({
  'model' : IDL.Text,
  'serviceType' : ServiceType,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'serviceInterval' : IDL.Nat,
  'brand' : IDL.Text,
  'installationDate' : Time,
});
export const ImportResult = IDL.Record({
  'errors' : IDL.Vec(IDL.Text),
  'successCount' : IDL.Nat,
  'failureCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAMCServiceEntry' : IDL.Func(
      [
        IDL.Nat,
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(
          IDL.Record({
            'partsName' : IDL.Text,
            'discountPrice' : IDL.Text,
            'regularPrice' : IDL.Text,
          })
        ),
      ],
      [AMCServiceEntry],
      [],
    ),
  'addAmcForCustomers' : IDL.Func(
      [IDL.Vec(IDL.Nat), AMCType, IDL.Nat, Time, Time],
      [],
      [],
    ),
  'addCustomer' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ServiceType,
        Time,
        IDL.Nat,
        IDL.Opt(AMCDetails),
        IDL.Text,
        IDL.Text,
      ],
      [Customer],
      [],
    ),
  'addReminder' : IDL.Func([IDL.Nat, Time, IDL.Text], [Reminder], []),
  'addServiceEntry' : IDL.Func(
      [
        IDL.Nat,
        Time,
        ServiceType,
        IDL.Nat,
        PaymentStatus,
        IDL.Opt(PaymentMethod),
        IDL.Text,
        IDL.Bool,
      ],
      [ServiceEntry],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteServiceEntry' : IDL.Func([IDL.Nat], [], []),
  'getAMCRevenue' : IDL.Func([], [AMCRevenue], ['query']),
  'getAMCServiceHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AMCServiceEntry)],
      ['query'],
    ),
  'getAllAMCs' : IDL.Func([], [IDL.Vec(AMCDetails)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(ServiceEntry)], ['query']),
  'getAmcRenewalsByUser' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getCustomerRevenueBreakdown' : IDL.Func(
      [],
      [IDL.Vec(CustomerRevenueBreakdown)],
      ['query'],
    ),
  'getCustomersByWarrantyStatus' : IDL.Func(
      [WarrantyStatus],
      [IDL.Vec(Customer)],
      ['query'],
    ),
  'getCustomersDueForServiceCurrentMonth' : IDL.Func(
      [],
      [IDL.Vec(Customer)],
      ['query'],
    ),
  'getPaymentMethodBreakdown' : IDL.Func(
      [],
      [PaymentMethodBreakdown],
      ['query'],
    ),
  'getRevenueByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [RevenueByPeriod],
      ['query'],
    ),
  'getRevenueByQuarter' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [RevenueByPeriod],
      ['query'],
    ),
  'getRevenueByYear' : IDL.Func([IDL.Nat], [RevenueByPeriod], ['query']),
  'getServiceHistory' : IDL.Func([IDL.Nat], [IDL.Vec(ServiceEntry)], ['query']),
  'getTodaysReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getUnpaidServices' : IDL.Func([], [IDL.Vec(ServiceEntry)], ['query']),
  'getUpcomingReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getUpcomingServices' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getWarrantyStatusCounts' : IDL.Func(
      [],
      [IDL.Record({ 'outWarranty' : IDL.Nat, 'inWarranty' : IDL.Nat })],
      ['query'],
    ),
  'importCustomers' : IDL.Func(
      [IDL.Vec(ImportCustomerData)],
      [ImportResult],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markServiceAsDone' : IDL.Func([IDL.Nat, Time], [], []),
  'multiDeleteCustomers' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'setReminderSentStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateCustomer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        ServiceType,
        Time,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(AMCDetails),
      ],
      [Customer],
      [],
    ),
  'updatePaymentStatus' : IDL.Func(
      [IDL.Nat, PaymentStatus, IDL.Opt(PaymentMethod)],
      [ServiceEntry],
      [],
    ),
  'updateServiceEntry' : IDL.Func(
      [
        IDL.Nat,
        Time,
        ServiceType,
        IDL.Nat,
        PaymentStatus,
        IDL.Opt(PaymentMethod),
        IDL.Text,
        IDL.Bool,
      ],
      [ServiceEntry],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const AMCType = IDL.Variant({
    'serviceWithParts50' : IDL.Null,
    'onlyService' : IDL.Null,
    'serviceWithParts' : IDL.Null,
  });
  const ContractStatus = IDL.Variant({
    'active' : IDL.Null,
    'pendingRenewal' : IDL.Null,
    'expired' : IDL.Null,
  });
  const AMCServiceEntry = IDL.Record({
    'serviceDate' : Time,
    'followUpNeeded' : IDL.Bool,
    'contractType' : AMCType,
    'priceReduction' : IDL.Opt(
      IDL.Record({
        'partsName' : IDL.Text,
        'discountPrice' : IDL.Text,
        'regularPrice' : IDL.Text,
      })
    ),
    'amcServiceId' : IDL.Nat,
    'notes' : IDL.Text,
    'partsReplaced' : IDL.Text,
    'customerServiceId' : IDL.Nat,
    'contractStatus' : ContractStatus,
  });
  const ServiceType = IDL.Variant({
    'repair' : IDL.Null,
    'cleaning' : IDL.Null,
    'other' : IDL.Text,
    'maintenance' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'upi' : IDL.Null, 'cash' : IDL.Null });
  const AMCDetails = IDL.Record({
    'id' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'durationYears' : IDL.Nat,
    'contractType' : AMCType,
    'contractEndDate' : Time,
    'remainingBalance' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'notes' : IDL.Text,
    'contractStartDate' : Time,
  });
  const AMCContract = IDL.Record({
    'endDate' : Time,
    'owner' : IDL.Principal,
    'contractType' : AMCType,
    'amount' : IDL.Nat,
    'startDate' : Time,
  });
  const WarrantyStatus = IDL.Variant({
    'outWarranty' : IDL.Null,
    'inWarranty' : IDL.Null,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'amcServices' : IDL.Vec(AMCServiceEntry),
    'model' : IDL.Text,
    'serviceType' : ServiceType,
    'contact' : IDL.Text,
    'owner' : IDL.Principal,
    'nextServiceDate' : Time,
    'amcDetails' : IDL.Opt(AMCDetails),
    'name' : IDL.Text,
    'amcContracts' : IDL.Vec(AMCContract),
    'serviceInterval' : IDL.Nat,
    'brand' : IDL.Text,
    'warrantyStatus' : WarrantyStatus,
    'installationDate' : Time,
  });
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'sentStatus' : IDL.Bool,
    'description' : IDL.Text,
    'reminderDate' : Time,
    'customerId' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'free' : IDL.Null,
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
  });
  const ServiceEntry = IDL.Record({
    'id' : IDL.Nat,
    'serviceDate' : Time,
    'serviceType' : ServiceType,
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : IDL.Opt(PaymentMethod),
    'owner' : IDL.Principal,
    'isFree' : IDL.Bool,
    'notes' : IDL.Text,
    'customerId' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AMCRevenue = IDL.Record({
    'completedAmount' : IDL.Nat,
    'inProgressAmount' : IDL.Nat,
    'remainingBalance' : IDL.Nat,
    'totalAmount' : IDL.Nat,
  });
  const CustomerRevenueBreakdown = IDL.Record({
    'customerName' : IDL.Text,
    'contractType' : IDL.Opt(AMCType),
    'paidServicesCount' : IDL.Nat,
    'amcRenewalCount' : IDL.Nat,
    'customerId' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'freeServicesCount' : IDL.Nat,
  });
  const PaymentMethodBreakdown = IDL.Record({
    'cashPayments' : IDL.Nat,
    'upiPayments' : IDL.Nat,
  });
  const RevenueByPeriod = IDL.Record({
    'paidServicesCount' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'freeServicesCount' : IDL.Nat,
  });
  const ImportCustomerData = IDL.Record({
    'model' : IDL.Text,
    'serviceType' : ServiceType,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'serviceInterval' : IDL.Nat,
    'brand' : IDL.Text,
    'installationDate' : Time,
  });
  const ImportResult = IDL.Record({
    'errors' : IDL.Vec(IDL.Text),
    'successCount' : IDL.Nat,
    'failureCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAMCServiceEntry' : IDL.Func(
        [
          IDL.Nat,
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(
            IDL.Record({
              'partsName' : IDL.Text,
              'discountPrice' : IDL.Text,
              'regularPrice' : IDL.Text,
            })
          ),
        ],
        [AMCServiceEntry],
        [],
      ),
    'addAmcForCustomers' : IDL.Func(
        [IDL.Vec(IDL.Nat), AMCType, IDL.Nat, Time, Time],
        [],
        [],
      ),
    'addCustomer' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ServiceType,
          Time,
          IDL.Nat,
          IDL.Opt(AMCDetails),
          IDL.Text,
          IDL.Text,
        ],
        [Customer],
        [],
      ),
    'addReminder' : IDL.Func([IDL.Nat, Time, IDL.Text], [Reminder], []),
    'addServiceEntry' : IDL.Func(
        [
          IDL.Nat,
          Time,
          ServiceType,
          IDL.Nat,
          PaymentStatus,
          IDL.Opt(PaymentMethod),
          IDL.Text,
          IDL.Bool,
        ],
        [ServiceEntry],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteServiceEntry' : IDL.Func([IDL.Nat], [], []),
    'getAMCRevenue' : IDL.Func([], [AMCRevenue], ['query']),
    'getAMCServiceHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AMCServiceEntry)],
        ['query'],
      ),
    'getAllAMCs' : IDL.Func([], [IDL.Vec(AMCDetails)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(ServiceEntry)], ['query']),
    'getAmcRenewalsByUser' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getCustomerRevenueBreakdown' : IDL.Func(
        [],
        [IDL.Vec(CustomerRevenueBreakdown)],
        ['query'],
      ),
    'getCustomersByWarrantyStatus' : IDL.Func(
        [WarrantyStatus],
        [IDL.Vec(Customer)],
        ['query'],
      ),
    'getCustomersDueForServiceCurrentMonth' : IDL.Func(
        [],
        [IDL.Vec(Customer)],
        ['query'],
      ),
    'getPaymentMethodBreakdown' : IDL.Func(
        [],
        [PaymentMethodBreakdown],
        ['query'],
      ),
    'getRevenueByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [RevenueByPeriod],
        ['query'],
      ),
    'getRevenueByQuarter' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [RevenueByPeriod],
        ['query'],
      ),
    'getRevenueByYear' : IDL.Func([IDL.Nat], [RevenueByPeriod], ['query']),
    'getServiceHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ServiceEntry)],
        ['query'],
      ),
    'getTodaysReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getUnpaidServices' : IDL.Func([], [IDL.Vec(ServiceEntry)], ['query']),
    'getUpcomingReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getUpcomingServices' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getWarrantyStatusCounts' : IDL.Func(
        [],
        [IDL.Record({ 'outWarranty' : IDL.Nat, 'inWarranty' : IDL.Nat })],
        ['query'],
      ),
    'importCustomers' : IDL.Func(
        [IDL.Vec(ImportCustomerData)],
        [ImportResult],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markServiceAsDone' : IDL.Func([IDL.Nat, Time], [], []),
    'multiDeleteCustomers' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'setReminderSentStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateCustomer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          ServiceType,
          Time,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(AMCDetails),
        ],
        [Customer],
        [],
      ),
    'updatePaymentStatus' : IDL.Func(
        [IDL.Nat, PaymentStatus, IDL.Opt(PaymentMethod)],
        [ServiceEntry],
        [],
      ),
    'updateServiceEntry' : IDL.Func(
        [
          IDL.Nat,
          Time,
          ServiceType,
          IDL.Nat,
          PaymentStatus,
          IDL.Opt(PaymentMethod),
          IDL.Text,
          IDL.Bool,
        ],
        [ServiceEntry],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };