/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AMCContract {
  'endDate' : Time,
  'owner' : Principal,
  'contractType' : AMCType,
  'amount' : bigint,
  'startDate' : Time,
}
export interface AMCDetails {
  'id' : bigint,
  'paymentMethod' : AMCPaymentMethod,
  'durationYears' : bigint,
  'contractType' : AMCType,
  'contractEndDate' : Time,
  'remainingBalance' : bigint,
  'totalAmount' : bigint,
  'notes' : string,
  'contractStartDate' : Time,
}
export type AMCPaymentMethod = { 'other' : string } |
  { 'cash' : null } |
  { 'bankTransfer' : null } |
  { 'cheque' : null } |
  { 'online' : null };
export interface AMCRevenue {
  'completedAmount' : bigint,
  'inProgressAmount' : bigint,
  'remainingBalance' : bigint,
  'totalAmount' : bigint,
}
export interface AMCServiceEntry {
  'serviceDate' : Time,
  'followUpNeeded' : boolean,
  'contractType' : AMCType,
  'priceReduction' : [] | [
    { 'partsName' : string, 'discountPrice' : string, 'regularPrice' : string }
  ],
  'amcServiceId' : bigint,
  'notes' : string,
  'partsReplaced' : string,
  'customerServiceId' : bigint,
  'contractStatus' : ContractStatus,
}
export type AMCType = { 'serviceWithParts50' : null } |
  { 'onlyService' : null } |
  { 'serviceWithParts' : null };
export type ContractStatus = { 'active' : null } |
  { 'pendingRenewal' : null } |
  { 'expired' : null };
export interface Customer {
  'id' : bigint,
  'amcServices' : Array<AMCServiceEntry>,
  'model' : string,
  'serviceType' : ServiceType,
  'contact' : string,
  'owner' : Principal,
  'nextServiceDate' : Time,
  'amcDetails' : [] | [AMCDetails],
  'name' : string,
  'amcContracts' : Array<AMCContract>,
  'serviceInterval' : bigint,
  'brand' : string,
  'warrantyStatus' : WarrantyStatus,
  'installationDate' : Time,
}
export interface CustomerRevenueBreakdown {
  'customerName' : string,
  'contractType' : [] | [AMCType],
  'paidServicesCount' : bigint,
  'amcRenewalCount' : bigint,
  'customerId' : bigint,
  'totalRevenue' : bigint,
  'freeServicesCount' : bigint,
}
export interface ImportCustomerData {
  'model' : string,
  'serviceType' : ServiceType,
  'contact' : string,
  'name' : string,
  'serviceInterval' : bigint,
  'brand' : string,
  'installationDate' : Time,
}
export interface ImportResult {
  'errors' : Array<string>,
  'successCount' : bigint,
  'failureCount' : bigint,
}
export type PaymentMethod = { 'upi' : null } |
  { 'cash' : null };
export interface PaymentMethodBreakdown {
  'otherPayments' : bigint,
  'cashPayments' : bigint,
  'bankTransfer' : bigint,
  'upiPayments' : bigint,
  'chequePayments' : bigint,
  'onlinePayments' : bigint,
}
export type PaymentStatus = { 'free' : null } |
  { 'paid' : null } |
  { 'unpaid' : null };
export interface Reminder {
  'id' : bigint,
  'owner' : Principal,
  'sentStatus' : boolean,
  'description' : string,
  'reminderDate' : Time,
  'customerId' : bigint,
}
export interface RevenueByPeriod {
  'paidServicesCount' : bigint,
  'totalRevenue' : bigint,
  'freeServicesCount' : bigint,
}
export interface ServiceEntry {
  'id' : bigint,
  'serviceDate' : Time,
  'serviceType' : ServiceType,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : [] | [PaymentMethod],
  'owner' : Principal,
  'isFree' : boolean,
  'notes' : string,
  'customerId' : bigint,
  'amount' : bigint,
}
export type ServiceType = { 'repair' : null } |
  { 'cleaning' : null } |
  { 'other' : string } |
  { 'maintenance' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WarrantyStatus = { 'outWarranty' : null } |
  { 'inWarranty' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAMCServiceEntry' : ActorMethod<
    [
      bigint,
      Time,
      string,
      string,
      boolean,
      [] | [
        {
          'partsName' : string,
          'discountPrice' : string,
          'regularPrice' : string,
        }
      ],
    ],
    AMCServiceEntry
  >,
  'addAmc' : ActorMethod<[bigint, AMCType, bigint, Time, Time], undefined>,
  'addCustomer' : ActorMethod<
    [
      string,
      string,
      ServiceType,
      Time,
      bigint,
      [] | [AMCDetails],
      string,
      string,
    ],
    Customer
  >,
  'addReminder' : ActorMethod<[bigint, Time, string], Reminder>,
  'addServiceEntry' : ActorMethod<
    [
      bigint,
      Time,
      ServiceType,
      bigint,
      PaymentStatus,
      [] | [PaymentMethod],
      string,
      boolean,
    ],
    ServiceEntry
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteServiceEntry' : ActorMethod<[bigint], undefined>,
  'getAMCRevenue' : ActorMethod<[], AMCRevenue>,
  'getAMCServiceHistory' : ActorMethod<[bigint], Array<AMCServiceEntry>>,
  'getAllAMCs' : ActorMethod<[], Array<AMCDetails>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllReminders' : ActorMethod<[], Array<Reminder>>,
  'getAllServices' : ActorMethod<[], Array<ServiceEntry>>,
  'getAmcRenewalsByUser' : ActorMethod<[Principal], bigint>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getCustomerRevenueBreakdown' : ActorMethod<
    [],
    Array<CustomerRevenueBreakdown>
  >,
  'getCustomersByWarrantyStatus' : ActorMethod<
    [WarrantyStatus],
    Array<Customer>
  >,
  'getCustomersDueForServiceCurrentMonth' : ActorMethod<[], Array<Customer>>,
  'getPaymentMethodBreakdown' : ActorMethod<[], PaymentMethodBreakdown>,
  'getRevenueByMonth' : ActorMethod<[bigint, bigint], RevenueByPeriod>,
  'getRevenueByQuarter' : ActorMethod<[bigint, bigint], RevenueByPeriod>,
  'getRevenueByYear' : ActorMethod<[bigint], RevenueByPeriod>,
  'getServiceHistory' : ActorMethod<[bigint], Array<ServiceEntry>>,
  'getTodaysReminders' : ActorMethod<[], Array<Reminder>>,
  'getUnpaidServices' : ActorMethod<[], Array<ServiceEntry>>,
  'getUpcomingReminders' : ActorMethod<[], Array<Reminder>>,
  'getUpcomingServices' : ActorMethod<[], Array<Customer>>,
  'getWarrantyStatusCounts' : ActorMethod<
    [],
    { 'outWarranty' : bigint, 'inWarranty' : bigint }
  >,
  'importCustomers' : ActorMethod<[Array<ImportCustomerData>], ImportResult>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markServiceAsDone' : ActorMethod<[bigint, Time], undefined>,
  'multiDeleteCustomers' : ActorMethod<[Array<bigint>], undefined>,
  'setReminderSentStatus' : ActorMethod<[bigint, boolean], undefined>,
  'updateCustomer' : ActorMethod<
    [
      bigint,
      string,
      string,
      ServiceType,
      Time,
      bigint,
      string,
      string,
      [] | [AMCDetails],
    ],
    Customer
  >,
  'updatePaymentStatus' : ActorMethod<
    [bigint, PaymentStatus, [] | [PaymentMethod]],
    ServiceEntry
  >,
  'updateServiceEntry' : ActorMethod<
    [
      bigint,
      Time,
      ServiceType,
      bigint,
      PaymentStatus,
      [] | [PaymentMethod],
      string,
      boolean,
    ],
    ServiceEntry
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];