/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AMCContract {
    endDate: Time;
    owner: Principal;
    contractType: AMCType;
    amount: bigint;
    startDate: Time;
}
export interface RevenueByPeriod {
    paidServicesCount: bigint;
    totalRevenue: bigint;
    freeServicesCount: bigint;
}
export type ServiceType = {
    __kind__: "repair";
    repair: null;
} | {
    __kind__: "cleaning";
    cleaning: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "maintenance";
    maintenance: null;
};
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PaymentMethodBreakdown {
    cashPayments: bigint;
    upiPayments: bigint;
}
export interface ImportResult {
    errors: Array<string>;
    successCount: bigint;
    failureCount: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Customer {
    id: bigint;
    amcServices: Array<AMCServiceEntry>;
    model: string;
    serviceType: ServiceType;
    contact: string;
    owner: Principal;
    nextServiceDate: Time;
    amcDetails?: AMCDetails;
    name: string;
    amcContracts: Array<AMCContract>;
    serviceInterval: bigint;
    brand: string;
    warrantyStatus: WarrantyStatus;
    installationDate: Time;
}
export interface CustomerRevenueBreakdown {
    customerName: string;
    contractType?: AMCType;
    paidServicesCount: bigint;
    amcRenewalCount: bigint;
    customerId: bigint;
    totalRevenue: bigint;
    freeServicesCount: bigint;
}
export interface Reminder {
    id: bigint;
    owner: Principal;
    sentStatus: boolean;
    description: string;
    reminderDate: Time;
    customerId: bigint;
}
export interface ImportCustomerData {
    model: string;
    serviceType: ServiceType;
    contact: string;
    name: string;
    serviceInterval: bigint;
    brand: string;
    installationDate: Time;
}
export interface AMCDetails {
    id: bigint;
    paymentMethod: PaymentMethod;
    durationYears: bigint;
    contractType: AMCType;
    contractEndDate: Time;
    remainingBalance: bigint;
    totalAmount: bigint;
    notes: string;
    contractStartDate: Time;
}
export interface ServiceEntry {
    id: bigint;
    serviceDate: Time;
    serviceType: ServiceType;
    paymentStatus: PaymentStatus;
    paymentMethod?: PaymentMethod;
    owner: Principal;
    isFree: boolean;
    notes: string;
    customerId: bigint;
    amount: bigint;
}
export interface AMCServiceEntry {
    serviceDate: Time;
    followUpNeeded: boolean;
    contractType: AMCType;
    priceReduction?: {
        partsName: string;
        discountPrice: string;
        regularPrice: string;
    };
    amcServiceId: bigint;
    notes: string;
    partsReplaced: string;
    customerServiceId: bigint;
    contractStatus: ContractStatus;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface AMCRevenue {
    completedAmount: bigint;
    inProgressAmount: bigint;
    remainingBalance: bigint;
    totalAmount: bigint;
}
export enum AMCType {
    serviceWithParts50 = "serviceWithParts50",
    onlyService = "onlyService",
    serviceWithParts = "serviceWithParts"
}
export enum ContractStatus {
    active = "active",
    pendingRenewal = "pendingRenewal",
    expired = "expired"
}
export enum PaymentMethod {
    upi = "upi",
    cash = "cash"
}
export enum PaymentStatus {
    free = "free",
    paid = "paid",
    unpaid = "unpaid"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WarrantyStatus {
    outWarranty = "outWarranty",
    inWarranty = "inWarranty"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAMCServiceEntry(customerId: bigint, serviceDate: Time, partsReplaced: string, notes: string, followUpNeeded: boolean, priceReduction: {
        partsName: string;
        discountPrice: string;
        regularPrice: string;
    } | null): Promise<AMCServiceEntry>;
    addAmcForCustomers(customerIds: Array<bigint>, contractType: AMCType, amount: bigint, startDate: Time, endDate: Time): Promise<void>;
    addCustomer(name: string, contact: string, serviceType: ServiceType, installationDate: Time, serviceInterval: bigint, amcDetails: AMCDetails | null, brand: string, model: string): Promise<Customer>;
    addReminder(customerId: bigint, reminderDate: Time, description: string): Promise<Reminder>;
    addServiceEntry(customerId: bigint, serviceDate: Time, serviceType: ServiceType, amount: bigint, paymentStatus: PaymentStatus, paymentMethod: PaymentMethod | null, notes: string, isFree: boolean): Promise<ServiceEntry>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCustomer(customerId: bigint): Promise<void>;
    deleteServiceEntry(serviceId: bigint): Promise<void>;
    getAMCRevenue(): Promise<AMCRevenue>;
    getAMCServiceHistory(customerId: bigint): Promise<Array<AMCServiceEntry>>;
    getAllAMCs(): Promise<Array<AMCDetails>>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllReminders(): Promise<Array<Reminder>>;
    getAllServices(): Promise<Array<ServiceEntry>>;
    getAmcRenewalsByUser(userId: Principal): Promise<bigint>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(id: bigint): Promise<Customer | null>;
    getCustomerRevenueBreakdown(): Promise<Array<CustomerRevenueBreakdown>>;
    getCustomersByWarrantyStatus(status: WarrantyStatus): Promise<Array<Customer>>;
    getCustomersDueForServiceCurrentMonth(): Promise<Array<Customer>>;
    getPaymentMethodBreakdown(): Promise<PaymentMethodBreakdown>;
    getRevenueByMonth(year: bigint, month: bigint): Promise<RevenueByPeriod>;
    getRevenueByQuarter(year: bigint, quarter: bigint): Promise<RevenueByPeriod>;
    getRevenueByYear(year: bigint): Promise<RevenueByPeriod>;
    getServiceHistory(customerId: bigint): Promise<Array<ServiceEntry>>;
    getTodaysReminders(): Promise<Array<Reminder>>;
    getUnpaidServices(): Promise<Array<ServiceEntry>>;
    getUpcomingReminders(): Promise<Array<Reminder>>;
    getUpcomingServices(): Promise<Array<Customer>>;
    getWarrantyStatusCounts(): Promise<{
        outWarranty: bigint;
        inWarranty: bigint;
    }>;
    importCustomers(customersData: Array<ImportCustomerData>): Promise<ImportResult>;
    isCallerAdmin(): Promise<boolean>;
    markServiceAsDone(customerId: bigint, serviceDoneDate: Time): Promise<void>;
    multiDeleteCustomers(ids: Array<bigint>): Promise<void>;
    setReminderSentStatus(reminderId: bigint, status: boolean): Promise<void>;
    updateCustomer(id: bigint, name: string, contact: string, serviceType: ServiceType, installationDate: Time, serviceInterval: bigint, brand: string, model: string, amcDetails: AMCDetails | null): Promise<Customer>;
    updatePaymentStatus(serviceId: bigint, status: PaymentStatus, paymentMethod: PaymentMethod | null): Promise<ServiceEntry>;
    updateServiceEntry(serviceId: bigint, serviceDate: Time, serviceType: ServiceType, amount: bigint, paymentStatus: PaymentStatus, paymentMethod: PaymentMethod | null, notes: string, isFree: boolean): Promise<ServiceEntry>;
}
import type { AMCContract as _AMCContract, AMCDetails as _AMCDetails, AMCServiceEntry as _AMCServiceEntry, AMCType as _AMCType, ContractStatus as _ContractStatus, Customer as _Customer, CustomerRevenueBreakdown as _CustomerRevenueBreakdown, ImportCustomerData as _ImportCustomerData, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, ServiceEntry as _ServiceEntry, ServiceType as _ServiceType, Time as _Time, UserRole as _UserRole, WarrantyStatus as _WarrantyStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAMCServiceEntry(arg0: bigint, arg1: Time, arg2: string, arg3: string, arg4: boolean, arg5: {
        partsName: string;
        discountPrice: string;
        regularPrice: string;
    } | null): Promise<AMCServiceEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addAMCServiceEntry(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
                return from_candid_AMCServiceEntry_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAMCServiceEntry(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
            return from_candid_AMCServiceEntry_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addAmcForCustomers(arg0: Array<bigint>, arg1: AMCType, arg2: bigint, arg3: Time, arg4: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAmcForCustomers(arg0, to_candid_AMCType_n16(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAmcForCustomers(arg0, to_candid_AMCType_n16(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async addCustomer(arg0: string, arg1: string, arg2: ServiceType, arg3: Time, arg4: bigint, arg5: AMCDetails | null, arg6: string, arg7: string): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, arg1, to_candid_ServiceType_n18(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return from_candid_Customer_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, arg1, to_candid_ServiceType_n18(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return from_candid_Customer_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async addReminder(arg0: bigint, arg1: Time, arg2: string): Promise<Reminder> {
        if (this.processError) {
            try {
                const result = await this.actor.addReminder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReminder(arg0, arg1, arg2);
            return result;
        }
    }
    async addServiceEntry(arg0: bigint, arg1: Time, arg2: ServiceType, arg3: bigint, arg4: PaymentStatus, arg5: PaymentMethod | null, arg6: string, arg7: boolean): Promise<ServiceEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addServiceEntry(arg0, arg1, to_candid_ServiceType_n18(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_PaymentStatus_n40(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return from_candid_ServiceEntry_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addServiceEntry(arg0, arg1, to_candid_ServiceType_n18(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_PaymentStatus_n40(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return from_candid_ServiceEntry_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n48(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n48(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCustomer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteServiceEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteServiceEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteServiceEntry(arg0);
            return result;
        }
    }
    async getAMCRevenue(): Promise<AMCRevenue> {
        if (this.processError) {
            try {
                const result = await this.actor.getAMCRevenue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAMCRevenue();
            return result;
        }
    }
    async getAMCServiceHistory(arg0: bigint): Promise<Array<AMCServiceEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAMCServiceHistory(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAMCServiceHistory(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAMCs(): Promise<Array<AMCDetails>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAMCs();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAMCs();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReminders();
            return result;
        }
    }
    async getAllServices(): Promise<Array<ServiceEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAmcRenewalsByUser(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAmcRenewalsByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAmcRenewalsByUser(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerRevenueBreakdown(): Promise<Array<CustomerRevenueBreakdown>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerRevenueBreakdown();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerRevenueBreakdown();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomersByWarrantyStatus(arg0: WarrantyStatus): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomersByWarrantyStatus(to_candid_WarrantyStatus_n60(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomersByWarrantyStatus(to_candid_WarrantyStatus_n60(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomersDueForServiceCurrentMonth(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomersDueForServiceCurrentMonth();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomersDueForServiceCurrentMonth();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentMethodBreakdown(): Promise<PaymentMethodBreakdown> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentMethodBreakdown();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentMethodBreakdown();
            return result;
        }
    }
    async getRevenueByMonth(arg0: bigint, arg1: bigint): Promise<RevenueByPeriod> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueByMonth(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueByMonth(arg0, arg1);
            return result;
        }
    }
    async getRevenueByQuarter(arg0: bigint, arg1: bigint): Promise<RevenueByPeriod> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueByQuarter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueByQuarter(arg0, arg1);
            return result;
        }
    }
    async getRevenueByYear(arg0: bigint): Promise<RevenueByPeriod> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueByYear(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueByYear(arg0);
            return result;
        }
    }
    async getServiceHistory(arg0: bigint): Promise<Array<ServiceEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceHistory(arg0);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceHistory(arg0);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodaysReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysReminders();
            return result;
        }
    }
    async getUnpaidServices(): Promise<Array<ServiceEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnpaidServices();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnpaidServices();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingReminders();
            return result;
        }
    }
    async getUpcomingServices(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingServices();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingServices();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWarrantyStatusCounts(): Promise<{
        outWarranty: bigint;
        inWarranty: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getWarrantyStatusCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWarrantyStatusCounts();
            return result;
        }
    }
    async importCustomers(arg0: Array<ImportCustomerData>): Promise<ImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.importCustomers(to_candid_vec_n62(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importCustomers(to_candid_vec_n62(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markServiceAsDone(arg0: bigint, arg1: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markServiceAsDone(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markServiceAsDone(arg0, arg1);
            return result;
        }
    }
    async multiDeleteCustomers(arg0: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.multiDeleteCustomers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.multiDeleteCustomers(arg0);
            return result;
        }
    }
    async setReminderSentStatus(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setReminderSentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setReminderSentStatus(arg0, arg1);
            return result;
        }
    }
    async updateCustomer(arg0: bigint, arg1: string, arg2: string, arg3: ServiceType, arg4: Time, arg5: bigint, arg6: string, arg7: string, arg8: AMCDetails | null): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1, arg2, to_candid_ServiceType_n18(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg8));
                return from_candid_Customer_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1, arg2, to_candid_ServiceType_n18(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg8));
            return from_candid_Customer_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePaymentStatus(arg0: bigint, arg1: PaymentStatus, arg2: PaymentMethod | null): Promise<ServiceEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n40(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg2));
                return from_candid_ServiceEntry_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n40(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg2));
            return from_candid_ServiceEntry_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateServiceEntry(arg0: bigint, arg1: Time, arg2: ServiceType, arg3: bigint, arg4: PaymentStatus, arg5: PaymentMethod | null, arg6: string, arg7: boolean): Promise<ServiceEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceEntry(arg0, arg1, to_candid_ServiceType_n18(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_PaymentStatus_n40(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return from_candid_ServiceEntry_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceEntry(arg0, arg1, to_candid_ServiceType_n18(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_PaymentStatus_n40(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return from_candid_ServiceEntry_n43(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AMCContract_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AMCContract): AMCContract {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_AMCDetails_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AMCDetails): AMCDetails {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_AMCServiceEntry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AMCServiceEntry): AMCServiceEntry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_AMCType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AMCType): AMCType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ContractStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContractStatus): ContractStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerRevenueBreakdown_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerRevenueBreakdown): CustomerRevenueBreakdown {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_Customer_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceEntry_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceEntry): ServiceEntry {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_WarrantyStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WarrantyStatus): WarrantyStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        partsName: string;
        discountPrice: string;
        regularPrice: string;
    }]): {
    partsName: string;
    discountPrice: string;
    regularPrice: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AMCDetails]): AMCDetails | null {
    return value.length === 0 ? null : from_candid_AMCDetails_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentMethod]): PaymentMethod | null {
    return value.length === 0 ? null : from_candid_PaymentMethod_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : from_candid_Customer_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AMCType]): AMCType | null {
    return value.length === 0 ? null : from_candid_AMCType_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceDate: _Time;
    followUpNeeded: boolean;
    contractType: _AMCType;
    priceReduction: [] | [{
            partsName: string;
            discountPrice: string;
            regularPrice: string;
        }];
    amcServiceId: bigint;
    notes: string;
    partsReplaced: string;
    customerServiceId: bigint;
    contractStatus: _ContractStatus;
}): {
    serviceDate: Time;
    followUpNeeded: boolean;
    contractType: AMCType;
    priceReduction?: {
        partsName: string;
        discountPrice: string;
        regularPrice: string;
    };
    amcServiceId: bigint;
    notes: string;
    partsReplaced: string;
    customerServiceId: bigint;
    contractStatus: ContractStatus;
} {
    return {
        serviceDate: value.serviceDate,
        followUpNeeded: value.followUpNeeded,
        contractType: from_candid_AMCType_n11(_uploadFile, _downloadFile, value.contractType),
        priceReduction: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.priceReduction)),
        amcServiceId: value.amcServiceId,
        notes: value.notes,
        partsReplaced: value.partsReplaced,
        customerServiceId: value.customerServiceId,
        contractStatus: from_candid_ContractStatus_n14(_uploadFile, _downloadFile, value.contractStatus)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    amcServices: Array<_AMCServiceEntry>;
    model: string;
    serviceType: _ServiceType;
    contact: string;
    owner: Principal;
    nextServiceDate: _Time;
    amcDetails: [] | [_AMCDetails];
    name: string;
    amcContracts: Array<_AMCContract>;
    serviceInterval: bigint;
    brand: string;
    warrantyStatus: _WarrantyStatus;
    installationDate: _Time;
}): {
    id: bigint;
    amcServices: Array<AMCServiceEntry>;
    model: string;
    serviceType: ServiceType;
    contact: string;
    owner: Principal;
    nextServiceDate: Time;
    amcDetails?: AMCDetails;
    name: string;
    amcContracts: Array<AMCContract>;
    serviceInterval: bigint;
    brand: string;
    warrantyStatus: WarrantyStatus;
    installationDate: Time;
} {
    return {
        id: value.id,
        amcServices: from_candid_vec_n27(_uploadFile, _downloadFile, value.amcServices),
        model: value.model,
        serviceType: from_candid_ServiceType_n28(_uploadFile, _downloadFile, value.serviceType),
        contact: value.contact,
        owner: value.owner,
        nextServiceDate: value.nextServiceDate,
        amcDetails: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.amcDetails)),
        name: value.name,
        amcContracts: from_candid_vec_n35(_uploadFile, _downloadFile, value.amcContracts),
        serviceInterval: value.serviceInterval,
        brand: value.brand,
        warrantyStatus: from_candid_WarrantyStatus_n38(_uploadFile, _downloadFile, value.warrantyStatus),
        installationDate: value.installationDate
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    paymentMethod: _PaymentMethod;
    durationYears: bigint;
    contractType: _AMCType;
    contractEndDate: _Time;
    remainingBalance: bigint;
    totalAmount: bigint;
    notes: string;
    contractStartDate: _Time;
}): {
    id: bigint;
    paymentMethod: PaymentMethod;
    durationYears: bigint;
    contractType: AMCType;
    contractEndDate: Time;
    remainingBalance: bigint;
    totalAmount: bigint;
    notes: string;
    contractStartDate: Time;
} {
    return {
        id: value.id,
        paymentMethod: from_candid_PaymentMethod_n33(_uploadFile, _downloadFile, value.paymentMethod),
        durationYears: value.durationYears,
        contractType: from_candid_AMCType_n11(_uploadFile, _downloadFile, value.contractType),
        contractEndDate: value.contractEndDate,
        remainingBalance: value.remainingBalance,
        totalAmount: value.totalAmount,
        notes: value.notes,
        contractStartDate: value.contractStartDate
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate: _Time;
    owner: Principal;
    contractType: _AMCType;
    amount: bigint;
    startDate: _Time;
}): {
    endDate: Time;
    owner: Principal;
    contractType: AMCType;
    amount: bigint;
    startDate: Time;
} {
    return {
        endDate: value.endDate,
        owner: value.owner,
        contractType: from_candid_AMCType_n11(_uploadFile, _downloadFile, value.contractType),
        amount: value.amount,
        startDate: value.startDate
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    serviceDate: _Time;
    serviceType: _ServiceType;
    paymentStatus: _PaymentStatus;
    paymentMethod: [] | [_PaymentMethod];
    owner: Principal;
    isFree: boolean;
    notes: string;
    customerId: bigint;
    amount: bigint;
}): {
    id: bigint;
    serviceDate: Time;
    serviceType: ServiceType;
    paymentStatus: PaymentStatus;
    paymentMethod?: PaymentMethod;
    owner: Principal;
    isFree: boolean;
    notes: string;
    customerId: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        serviceDate: value.serviceDate,
        serviceType: from_candid_ServiceType_n28(_uploadFile, _downloadFile, value.serviceType),
        paymentStatus: from_candid_PaymentStatus_n45(_uploadFile, _downloadFile, value.paymentStatus),
        paymentMethod: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.paymentMethod)),
        owner: value.owner,
        isFree: value.isFree,
        notes: value.notes,
        customerId: value.customerId,
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    contractType: [] | [_AMCType];
    paidServicesCount: bigint;
    amcRenewalCount: bigint;
    customerId: bigint;
    totalRevenue: bigint;
    freeServicesCount: bigint;
}): {
    customerName: string;
    contractType?: AMCType;
    paidServicesCount: bigint;
    amcRenewalCount: bigint;
    customerId: bigint;
    totalRevenue: bigint;
    freeServicesCount: bigint;
} {
    return {
        customerName: value.customerName,
        contractType: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.contractType)),
        paidServicesCount: value.paidServicesCount,
        amcRenewalCount: value.amcRenewalCount,
        customerId: value.customerId,
        totalRevenue: value.totalRevenue,
        freeServicesCount: value.freeServicesCount
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceWithParts50: null;
} | {
    onlyService: null;
} | {
    serviceWithParts: null;
}): AMCType {
    return "serviceWithParts50" in value ? AMCType.serviceWithParts50 : "onlyService" in value ? AMCType.onlyService : "serviceWithParts" in value ? AMCType.serviceWithParts : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pendingRenewal: null;
} | {
    expired: null;
}): ContractStatus {
    return "active" in value ? ContractStatus.active : "pendingRenewal" in value ? ContractStatus.pendingRenewal : "expired" in value ? ContractStatus.expired : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    repair: null;
} | {
    cleaning: null;
} | {
    other: string;
} | {
    maintenance: null;
}): {
    __kind__: "repair";
    repair: null;
} | {
    __kind__: "cleaning";
    cleaning: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "maintenance";
    maintenance: null;
} {
    return "repair" in value ? {
        __kind__: "repair",
        repair: value.repair
    } : "cleaning" in value ? {
        __kind__: "cleaning",
        cleaning: value.cleaning
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "maintenance" in value ? {
        __kind__: "maintenance",
        maintenance: value.maintenance
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    cash: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "cash" in value ? PaymentMethod.cash : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    outWarranty: null;
} | {
    inWarranty: null;
}): WarrantyStatus {
    return "outWarranty" in value ? WarrantyStatus.outWarranty : "inWarranty" in value ? WarrantyStatus.inWarranty : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    free: null;
} | {
    paid: null;
} | {
    unpaid: null;
}): PaymentStatus {
    return "free" in value ? PaymentStatus.free : "paid" in value ? PaymentStatus.paid : "unpaid" in value ? PaymentStatus.unpaid : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AMCServiceEntry>): Array<AMCServiceEntry> {
    return value.map((x)=>from_candid_AMCServiceEntry_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AMCContract>): Array<AMCContract> {
    return value.map((x)=>from_candid_AMCContract_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AMCDetails>): Array<AMCDetails> {
    return value.map((x)=>from_candid_AMCDetails_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceEntry>): Array<ServiceEntry> {
    return value.map((x)=>from_candid_ServiceEntry_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerRevenueBreakdown>): Array<CustomerRevenueBreakdown> {
    return value.map((x)=>from_candid_CustomerRevenueBreakdown_n57(_uploadFile, _downloadFile, x));
}
function to_candid_AMCDetails_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AMCDetails): _AMCDetails {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_AMCType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AMCType): _AMCType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_ImportCustomerData_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImportCustomerData): _ImportCustomerData {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_WarrantyStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WarrantyStatus): _WarrantyStatus {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AMCDetails | null): [] | [_AMCDetails] {
    return value === null ? candid_none() : candid_some(to_candid_AMCDetails_n21(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod | null): [] | [_PaymentMethod] {
    return value === null ? candid_none() : candid_some(to_candid_PaymentMethod_n23(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    partsName: string;
    discountPrice: string;
    regularPrice: string;
} | null): [] | [{
        partsName: string;
        discountPrice: string;
        regularPrice: string;
    }] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    paymentMethod: PaymentMethod;
    durationYears: bigint;
    contractType: AMCType;
    contractEndDate: Time;
    remainingBalance: bigint;
    totalAmount: bigint;
    notes: string;
    contractStartDate: Time;
}): {
    id: bigint;
    paymentMethod: _PaymentMethod;
    durationYears: bigint;
    contractType: _AMCType;
    contractEndDate: _Time;
    remainingBalance: bigint;
    totalAmount: bigint;
    notes: string;
    contractStartDate: _Time;
} {
    return {
        id: value.id,
        paymentMethod: to_candid_PaymentMethod_n23(_uploadFile, _downloadFile, value.paymentMethod),
        durationYears: value.durationYears,
        contractType: to_candid_AMCType_n16(_uploadFile, _downloadFile, value.contractType),
        contractEndDate: value.contractEndDate,
        remainingBalance: value.remainingBalance,
        totalAmount: value.totalAmount,
        notes: value.notes,
        contractStartDate: value.contractStartDate
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    model: string;
    serviceType: ServiceType;
    contact: string;
    name: string;
    serviceInterval: bigint;
    brand: string;
    installationDate: Time;
}): {
    model: string;
    serviceType: _ServiceType;
    contact: string;
    name: string;
    serviceInterval: bigint;
    brand: string;
    installationDate: _Time;
} {
    return {
        model: value.model,
        serviceType: to_candid_ServiceType_n18(_uploadFile, _downloadFile, value.serviceType),
        contact: value.contact,
        name: value.name,
        serviceInterval: value.serviceInterval,
        brand: value.brand,
        installationDate: value.installationDate
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AMCType): {
    serviceWithParts50: null;
} | {
    onlyService: null;
} | {
    serviceWithParts: null;
} {
    return value == AMCType.serviceWithParts50 ? {
        serviceWithParts50: null
    } : value == AMCType.onlyService ? {
        onlyService: null
    } : value == AMCType.serviceWithParts ? {
        serviceWithParts: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "repair";
    repair: null;
} | {
    __kind__: "cleaning";
    cleaning: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "maintenance";
    maintenance: null;
}): {
    repair: null;
} | {
    cleaning: null;
} | {
    other: string;
} | {
    maintenance: null;
} {
    return value.__kind__ === "repair" ? {
        repair: value.repair
    } : value.__kind__ === "cleaning" ? {
        cleaning: value.cleaning
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "maintenance" ? {
        maintenance: value.maintenance
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    cash: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    free: null;
} | {
    paid: null;
} | {
    unpaid: null;
} {
    return value == PaymentStatus.free ? {
        free: null
    } : value == PaymentStatus.paid ? {
        paid: null
    } : value == PaymentStatus.unpaid ? {
        unpaid: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WarrantyStatus): {
    outWarranty: null;
} | {
    inWarranty: null;
} {
    return value == WarrantyStatus.outWarranty ? {
        outWarranty: null
    } : value == WarrantyStatus.inWarranty ? {
        inWarranty: null
    } : value;
}
function to_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ImportCustomerData>): Array<_ImportCustomerData> {
    return value.map((x)=>to_candid_ImportCustomerData_n63(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
